[project]
name = "easy-su-cloud-sdk"
version = "1.0.0"
description = "易速云SDK"
readme = "README.md"
requires-python = ">=3.12"
homepage = "https://github.com/Justwannasleep/easy_su_cloud_sdk"
repository = { url = "https://github.com/Justwannasleep/easy_su_cloud_sdk.git" }
dependencies = [
    "loguru>=0.7.3",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "requests>=2.32.4",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"